### ISSUE TITLE
Register - window

### ISSUE THREAD

**Issue by ljovic** [PaulaIvanovic/Projekt-FlashCards#10]
### Related:
#4  **GUI Creation**

### Description:
Create Register Window which is based on the discussed design (photo attached below). The Register Window needs to open in the middle of the screen and should be a fixed size.
All input fields need to have a placeholder and an appropriate label. The password input field should have hidden characters. All buttons should function, for the button "Register" the window should close, for the button "Login" the window should close and open the Login Window. 

### Mandatory elements:
- [ ] input field for username along with a label
- [ ] input field for email along with a label
- [ ] input field for password, characters are hidden, along with a label
- [ ] button Login
- [ ] button Register 
- [ ] logo of the app
- [ ] name of the app

### Development:
- [ ] button Login needs to close and change the current window to Login Window 

### Testing:
Register Window closely resembles the attached photo, opens in the middle of the screen and has a fixed height and width. All input fields work and the password field does not show characters. All the buttons work as described above.

### Attachment:
![Register](https://github.com/PaulaIvanovic/Projekt-FlashCards/assets/93715576/798cbd51-af19-470f-bd39-79870797614c)
*** further design modifications are allowed with the permission of at least three team members

For help, further specification or issue modification contact Paula Ivanović or another team member.

**Comment by PaulaIvanovic** [comment]
Branch tested and approved for merge.
