### ISSUE TITLE
Fix responsiveness of the windows

### ISSUE THREAD

**Issue by ljovic** [PaulaIvanovic/Projekt-FlashCards#35]
### Related:
#9 Group of cards display - window #11 Subgroups of cards - window

### Description:
Resolve existing issues within the specified (related) windows and ensure their proper integration. It is necessary to modify the window responsiveness. For example, when the window is at its default size (full-screen), 15 cards are displayed per page. If the user minimizes the window, the number of cards displayed should decrease accordingly, and additional pages should be introduced to accommodate the reduced visibility per page.

*** further design modifications are allowed with the permission of at least three team members

For help, further specification or issue modification contact Paula Ivanović or another team member.

**Comment by HanaDzin** [comment]
Instead of using pagination, the window has been made responsive using scroll option.
