### ISSUE TITLE
Login - window

### ISSUE THREAD

**Issue by ljovic** [PaulaIvanovic/Projekt-FlashCards#7]
### Related:
#4  **GUI Creation**

### Description:
Create Login Window which is based on the discussed design (photo attached below). The Login Window needs to open in the middle of the screen and should be a fixed size.
All input fields need to have a placeholder and an appropriate label. The password input field should have hidden characters. All buttons should function, for the button "Login" the window should close, for the button Register the window should close and open the Register Window. 

### Mandatory elements:
- [ ] input field for username along with a label
- [ ] input field for password, characters are hidden, along with a label
- [ ] button Login
- [ ] button Register 
- [ ] logo of the app
- [ ] name of the app

### Development:
- [ ] button Register needs to close and change the current window to Register Window 

### Testing:
Login Window closely resembles the attached photo, opens in the middle of the screen and has a fixed height and width. All input fields work and the password field does not show characters. All the buttons work as described above.

### Attachment:
![Login](https://github.com/PaulaIvanovic/Projekt-FlashCards/assets/93715576/16385094-cee5-4a8c-a0d2-4ca09ca482bb)
*** further design modifications are allowed with the permission of at least three team members

### Bugs:

For help, further specification or issue modification contact Paula Ivanović or another team member.

**Comment by PaulaIvanovic** [comment]
Branch tested and approved for merge.
