### ISSUE TITLE
Group of cards display - window

### ISSUE THREAD

**Issue by ljovic** [PaulaIvanovic/Projekt-FlashCards#9]
### Related:
#4 GUI Creation 

### Description:
Create Group of cards display window which allow the user to view their group of cards. 
The window should have all the groups of cards which the user can click on(and they lead user to the subgroup display window). All groups of cards should have a name. 
The toolbar should contain edit button, add a new group button, settings button and profile picture.

### Mandatory elements:

- [x] Toolbar - button to edit
- [x] Toolbar - button to add group
- [x] Toolbar - button to go to settings
- [x] Toolbar - user picture

### Development:
- [ ] toolbar button "Edit" should open pop-up window in which you can edit the group of cards
- [ ] toolbar button "Add" should add a new group
- [ ] toolbar button "Settings" should open settings
- [ ] on-click group of card leads to the next window

all buttons/icons described above need to be clickable
### Testing:
For testing purposes use one group of cards as default, all other groups should be fetched from the database in later issues.
Cards display window closely resembles the attached photo. All the buttons work as described above.

### Attachment:
![image](https://github.com/PaulaIvanovic/Projekt-FlashCards/assets/163010129/56a528e1-dc1f-4924-9426-9c179f76e75c)

*** further design modifications are allowed with the permission of at least three team members

For help, further specification or issue modification contact Paula Ivanović or another team member.

**Comment by PaulaIvanovic** [comment]
Branch tested and approved for merge.
